server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Signup Service
        - id: signup-service
          uri: http://localhost:8084
          predicates:
            - Path=/signup/**
          filters:
            - JwtAuthFilter

        # Signin Service
        - id: signin-service
          uri: http://localhost:8081
          predicates:
            - Path=/signin/**
          filters:
            - JwtAuthFilter
